# INFORMAÇÃO EXTRAS: INICIALIZAÇÃO DE UMA LISTA 

# EM ALGUMAS SITUAÇÕES É NECESSÁRIO DECLARAR E JÁ ATRIBUIR UM CONJUNTO DE VALORES CONSTANTES PARA UMA LISTA.
# DENTRO DA LISTA INCLUIMOS  UMA CONSTRUÇÃO COM UM LAÇO QUE GERARÁ VALORES INICIAIS PARA A LISTA.

x = [0 for i in range (5)]
print(x)
[0,0,0,0,0]

x = [2*1 for i in range (5)]
print (x)
[0,2,4,6,8]
