algoritmo "semnome"
// Função :
// Autor :
// Data : 18/08/2025
// Seção de Declarações 
var
n1, n2, n3, n4, soma, media :real
inicio
// Seção de Comandos 
Escreva("Digite o valor 1: ")
Leia(n1)
Escreva("Digite o valor 2: ")
Leia(n2)
Escreva("Digite o valor 3: ")
Leia(n3)
Escreva("Digite o valor 4: ")
Leia(n4)

soma :=n1+n2+n3+n4
media :=soma/4

Escreval("Soma = ",soma)
Escreval("Média = ",media)
fimalgoritmo
