algoritmo "L02I"
// Função: Verificar se um número é par ou ímpar
// Autor: Mhell Barroca Novaes
// Data : 24/08/2025
// Seção de Declarações
//i. Elaborar um programa que efetue a leitura de um número inteiro e apresentar uma mensagem informando se o número é par ou ímpar.
var

inicio
// Seção de Comandos

escreval("Digite um número: ")
leia(num)

se num mod 2 = 0 entao
   escreval("O número é par.")
senao
   escreval("O número é ímpar.")
fimse
fimalgoritmo
