algoritmo "L02J"
// Função: Verificar se número está entre 1 e 9
// Autor: Mhell Barroca Novaes
// Data : 24/08/2025
// Seção de Declarações
//j. Elaborar um programa que efetue a leitura de um valor que esteja entre a faixa de 1 a 9.
var
num: inteiro
inicio
// Seção de Comandos
escreval("Digite um número entre 1 e 9: ")
leia(num)

se (num >= 1) e (num <= 9) entao
   escreval("O valor está na faixa permitida.")
senao
   escreval("O valor está fora da faixa permitida.")
fimse
fimalgoritmo
